const $ = id => document.getElementById(id);
let lastRun = null;
const names = {retrieve:'Retrieve documents',grade_documents:'Grade documents',rewrite_query:'Rewrite query',retrieve_again:'Retrieve again · BM25',web_search:'External web search',generate_answer:'Generate answer'};
function node(tag, text, className) {const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
async function readJSON(url, options) {const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Invalid request. Check your question and settings.');return data;}
async function config() {try{const data=await readJSON('/api/config');$('model-name').textContent=data.model;$('doc-count').textContent=data.document_count;$('connection').textContent=data.live_ready?'EURI KEY CONFIGURED':'DEMO READY · ADD KEY FOR LIVE';}catch{$('connection').textContent='SERVER UNAVAILABLE';}}
config();
document.querySelectorAll('[data-example]').forEach(button=>button.onclick=()=>{$('question').value=button.dataset.example;$('question').focus();});
document.querySelectorAll('[name=mode]').forEach(input=>input.onchange=()=>{$('mode-note').textContent=input.value==='live'?'Calls EURI for grading, rewriting, and generation. Requires your server-side key.':'Deterministic grading and source excerpts. No API calls.';});
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(tab=>{const active=tab===button;tab.setAttribute('aria-selected',String(active));$(tab.dataset.tab).hidden=!active;});});
function render(result) {
  lastRun=result;$('empty-state').hidden=true;$('result').hidden=false;$('download').disabled=false;
  $('metrics').replaceChildren();
  for(const [label,value] of [['Relevance',Math.round(result.quality*100)+'%'],['Corrections',result.retries],['Sources',result.relevant_documents.length],['Run time',result.elapsed_seconds+'s']]){const metric=node('div',undefined,'metric');metric.append(node('small',label),node('strong',String(value)));$('metrics').append(metric);}
  $('result-mode').textContent=result.mode==='demo'?'OFFLINE DEMO · Heuristic grading and extractive excerpts. No EURI calls.':`LIVE EURI · ${result.model}`;
  $('answer').textContent=result.answer;$('warnings').replaceChildren(...result.warnings.map(w=>node('p',w,'help')));
  $('sources').replaceChildren();
  for(const doc of result.relevant_documents){const source=node(/^https?:\/\//.test(doc.source)?'a':'span',doc.id,'source-tag');source.title=doc.title+' · '+doc.source;if(source.tagName==='A'){source.href=doc.source;source.target='_blank';source.rel='noopener noreferrer';}$('sources').append(source);}
  $('evidence-panel').replaceChildren();
  const retrieved=new Map();
  for(const step of result.trace){if(step.documents)for(const doc of step.documents)retrieved.set(doc.id,doc);if(step.grades){const group=node('div');group.append(node('p',`Attempt ${step.attempt} · ${Math.round(step.quality*100)}% relevant`,'help'));if(!step.grades.length)group.append(node('p','No documents retrieved.','help'));for(const grade of step.grades){const doc=retrieved.get(grade.id);const card=node('article',undefined,'evidence');const heading=node('h3',doc?.title||grade.id);heading.append(node('span',grade.relevant?'RELEVANT':'IRRELEVANT','grade-label'+(grade.relevant?'':' rejected')));card.append(heading,node('p',grade.reason),node('p',doc?.text||''),node('p',doc?.source||'', 'help'));group.append(card);}$('evidence-panel').append(group);}}
  $('trace-panel').replaceChildren();
  result.trace.forEach((step,i)=>{const item=node('article',undefined,'trace-step');item.append(node('h3',`${String(i+1).padStart(2,'0')}  ${names[step.node]}`),node('p',step.detail));if(step.node==='rewrite_query')item.append(node('pre',`${step.query}\n↓\n${step.rewritten_query}`));else item.append(node('p',`Attempt ${step.attempt} · Query: ${step.query}`));if(step.decision)item.append(node('p',`Conditional edge → ${step.decision}`));$('trace-panel').append(item);});
  document.querySelectorAll('.flow-node').forEach(n=>{const visited=result.trace.some(s=>s.node===n.dataset.node||(s.node==='web_search'&&n.dataset.node==='retrieve_again'));n.classList.toggle('visited',visited);n.classList.toggle('corrected',visited&&['rewrite_query','retrieve_again'].includes(n.dataset.node));});
  $('run-state').textContent=result.outcome.replaceAll('_',' ').toUpperCase();
  document.querySelector('[data-tab="answer-panel"]').click();
}
$('question-form').onsubmit=async event=>{event.preventDefault();$('error').hidden=true;$('run-button').disabled=true;$('run-button').firstElementChild.textContent='Running workflow…';$('run-state').textContent='RUNNING';document.querySelector('.workflow-card').classList.add('busy');$('result').hidden=true;$('empty-state').hidden=false;$('empty-state').querySelector('h3').textContent='Retrieving, grading, and checking the evidence…';$('download').disabled=true;lastRun=null;document.querySelectorAll('.flow-node').forEach(n=>n.classList.remove('visited','corrected'));try{const result=await readJSON('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:$('question').value,mode:document.querySelector('[name=mode]:checked').value,top_k:Number($('top-k').value),max_retries:Number($('max-retries').value),relevance_threshold:Number($('threshold').value),use_web:$('use-web').checked})});render(result);}catch(error){$('error').textContent=error.message;$('error').hidden=false;$('run-state').textContent='FAILED';$('empty-state').querySelector('h3').textContent='The workflow could not complete. See the error message.';}finally{$('run-button').disabled=false;$('run-button').firstElementChild.textContent='Run workflow';document.querySelector('.workflow-card').classList.remove('busy');config();}};
$('download').onclick=()=>{if(!lastRun)return;const url=URL.createObjectURL(new Blob([JSON.stringify(lastRun,null,2)],{type:'application/json'}));const link=node('a');link.href=url;link.download=`crag-${lastRun.mode}-trace.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('show-corpus').onclick=async()=>{try{const docs=await readJSON('/api/documents');$('corpus-list').replaceChildren(...docs.map(doc=>{const item=node('article',undefined,'evidence');item.append(node('h3',doc.title),node('p',doc.text),node('p',`${doc.id} · ${doc.source}`,'help'));return item;}));$('corpus-dialog').showModal();}catch(error){$('error').textContent=error.message;$('error').hidden=false;}};
$('close-corpus').onclick=()=>$('corpus-dialog').close();
